baseURL = 'https://dearbobby9.github.io/'
defaultContentLanguage = "en"  # 默认语言为英文
title = 'Difan Jia'
theme = 'gokarna'

# Gokarna 特定设置
enableRobotsTXT = true
enableEmoji = true

# 语言设置
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Difan Jia"
    
    [languages.en.params]
      description = "Welcome to my personal website. Let's change the world together!"

  [languages.zh]
    languageName = "中文"
    weight = 2
    title = "贾迪帆"
    hasCJKLanguage = true
    languageCode = "zh-CN"
    
    [languages.zh.params]
      description = "欢迎来到我的个人网站，让我们一起改变世界！"

[params]
  # 个人信息设置
  author = "Your Name"
  avatarURL = "/images/avatar.png"
  
  # 网站设置
  showBackToTopButton = true
  
  # 社交媒体链接
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/bobby-jia-09738b28b"},
    {name = "twitter", url = "https://x.com/KeithMaxwell99"},
    {name = "email", url = "mailto:bobby003@umn.edu"}
  ]

  # 添加语言切换
  defaultTheme = "auto"
  ShowLanguageSelector = true

# 英文菜单
[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[languages.en.menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 4
  [[languages.en.menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
  [[languages.en.menu.main]]
    name = "中文"
    url = "/zh/"
    weight = 6

# 中文菜单
[languages.zh.menu]
  [[languages.zh.menu.main]]
    name = "首页"
    url = "/zh/"
    weight = 1
  [[languages.zh.menu.main]]
    name = "关于"
    url = "/zh/about/"
    weight = 2
  [[languages.zh.menu.main]]
    name = "项目"
    url = "/zh/projects/"
    weight = 3
  [[languages.zh.menu.main]]
    name = "博客"
    url = "/zh/posts/"
    weight = 4
  [[languages.zh.menu.main]]
    name = "标签"
    url = "/zh/tags/"
    weight = 5
  [[languages.zh.menu.main]]
    name = "English"
    url = "/"
    weight = 6
